[2025-03-12T06:18:32.615+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/api.py
[2025-03-12T06:18:32.618+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:18:32.622+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:18:32.621+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:18:32.634+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:18:32.629+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:18:32.634+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:18:32.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.042 seconds
[2025-03-12T06:19:02.953+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/api.py
[2025-03-12T06:19:02.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:19:02.956+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:19:02.956+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:19:02.963+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:19:02.959+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:19:02.963+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:19:02.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.023 seconds
[2025-03-12T06:19:33.274+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/api.py
[2025-03-12T06:19:33.275+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:19:33.278+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:19:33.278+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:19:33.288+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:19:33.285+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:19:33.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:19:33.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:20:03.581+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/api.py
[2025-03-12T06:20:03.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:20:03.584+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:20:03.584+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:20:03.594+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:20:03.592+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:20:03.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:20:03.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:20:33.888+0000] {processor.py:157} INFO - Started process (PID=76) to work on /opt/airflow/dags/api.py
[2025-03-12T06:20:33.889+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:20:33.891+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:20:33.890+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:20:33.895+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:20:33.894+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:20:33.895+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:20:33.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.028 seconds
[2025-03-12T06:21:04.213+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/api.py
[2025-03-12T06:21:04.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:21:04.216+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:21:04.216+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:21:04.228+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:21:04.223+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:21:04.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:21:04.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:21:34.514+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/api.py
[2025-03-12T06:21:34.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:21:34.517+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:21:34.517+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:21:34.525+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:21:34.524+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:21:34.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:21:34.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.024 seconds
[2025-03-12T06:22:04.853+0000] {processor.py:157} INFO - Started process (PID=102) to work on /opt/airflow/dags/api.py
[2025-03-12T06:22:04.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:22:04.857+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:22:04.856+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:22:04.863+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:22:04.860+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:22:04.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:22:04.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.030 seconds
[2025-03-12T06:22:35.213+0000] {processor.py:157} INFO - Started process (PID=111) to work on /opt/airflow/dags/api.py
[2025-03-12T06:22:35.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:22:35.218+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:22:35.217+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:22:35.223+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:22:35.222+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:22:35.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:22:35.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:23:05.549+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/api.py
[2025-03-12T06:23:05.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:23:05.552+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:23:05.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:23:05.559+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:23:05.558+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:23:05.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:23:05.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.025 seconds
[2025-03-12T06:23:35.872+0000] {processor.py:157} INFO - Started process (PID=129) to work on /opt/airflow/dags/api.py
[2025-03-12T06:23:35.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:23:35.876+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:23:35.876+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:23:35.885+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:23:35.882+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:23:35.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:23:35.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:24:06.212+0000] {processor.py:157} INFO - Started process (PID=138) to work on /opt/airflow/dags/api.py
[2025-03-12T06:24:06.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:24:06.217+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:24:06.217+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:24:06.221+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:24:06.220+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:24:06.222+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:24:06.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:24:36.532+0000] {processor.py:157} INFO - Started process (PID=147) to work on /opt/airflow/dags/api.py
[2025-03-12T06:24:36.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:24:36.536+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:24:36.535+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:24:36.541+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:24:36.540+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:24:36.542+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:24:36.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.025 seconds
[2025-03-12T06:25:06.854+0000] {processor.py:157} INFO - Started process (PID=155) to work on /opt/airflow/dags/api.py
[2025-03-12T06:25:06.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:25:06.859+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:25:06.859+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:25:06.866+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:25:06.863+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:25:06.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:25:06.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:25:37.185+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/api.py
[2025-03-12T06:25:37.186+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:25:37.189+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:25:37.189+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:25:37.194+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:25:37.193+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:25:37.194+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:25:37.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.026 seconds
[2025-03-12T06:26:07.367+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/api.py
[2025-03-12T06:26:07.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:26:07.373+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:26:07.373+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:26:07.383+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:26:07.382+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:26:07.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:26:07.401+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-03-12T06:26:37.560+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/api.py
[2025-03-12T06:26:37.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:26:37.565+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:26:37.565+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:26:37.572+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:26:37.570+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:26:37.573+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:26:37.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:27:07.904+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/api.py
[2025-03-12T06:27:07.908+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:27:07.912+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:27:07.911+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:27:07.921+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:27:07.920+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:27:07.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:27:07.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.043 seconds
[2025-03-12T06:27:38.111+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/api.py
[2025-03-12T06:27:38.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:27:38.115+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:27:38.114+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:27:38.124+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:27:38.119+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:27:38.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:27:38.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:28:08.294+0000] {processor.py:157} INFO - Started process (PID=216) to work on /opt/airflow/dags/api.py
[2025-03-12T06:28:08.297+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:28:08.298+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:28:08.298+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:28:08.305+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:28:08.301+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:28:08.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:28:08.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.027 seconds
[2025-03-12T06:28:38.498+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/api.py
[2025-03-12T06:28:38.501+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:28:38.504+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:28:38.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:28:38.515+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:28:38.513+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:28:38.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:28:38.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.035 seconds
[2025-03-12T06:29:08.695+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/api.py
[2025-03-12T06:29:08.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:29:08.698+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:29:08.697+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:29:08.702+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:29:08.701+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:29:08.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:29:08.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:29:38.907+0000] {processor.py:157} INFO - Started process (PID=242) to work on /opt/airflow/dags/api.py
[2025-03-12T06:29:38.911+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:29:38.913+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:29:38.913+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:29:38.922+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:29:38.917+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:29:38.922+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:29:38.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:30:09.261+0000] {processor.py:157} INFO - Started process (PID=251) to work on /opt/airflow/dags/api.py
[2025-03-12T06:30:09.264+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:30:09.267+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:30:09.267+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:30:09.278+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:30:09.273+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:30:09.278+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:30:09.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.038 seconds
[2025-03-12T06:30:39.608+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/api.py
[2025-03-12T06:30:39.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:30:39.613+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:30:39.613+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:30:39.621+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:30:39.617+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:30:39.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:30:39.636+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.031 seconds
[2025-03-12T06:31:09.947+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/api.py
[2025-03-12T06:31:09.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:31:09.952+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:31:09.952+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:31:09.962+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:31:09.961+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:31:09.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:31:09.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-03-12T06:31:40.313+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/api.py
[2025-03-12T06:31:40.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:31:40.318+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:31:40.318+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:31:40.327+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:31:40.323+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:31:40.327+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:31:40.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.043 seconds
[2025-03-12T06:32:10.649+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/api.py
[2025-03-12T06:32:10.651+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:32:10.655+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:32:10.655+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:32:10.662+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:32:10.659+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:32:10.662+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:32:10.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.033 seconds
[2025-03-12T06:32:40.841+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/api.py
[2025-03-12T06:32:40.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:32:40.843+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:32:40.843+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:32:40.851+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:32:40.847+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:32:40.851+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:32:40.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.021 seconds
[2025-03-12T06:33:11.097+0000] {processor.py:157} INFO - Started process (PID=304) to work on /opt/airflow/dags/api.py
[2025-03-12T06:33:11.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:33:11.100+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:33:11.100+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:33:11.112+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:33:11.109+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:33:11.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:33:11.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:33:41.308+0000] {processor.py:157} INFO - Started process (PID=313) to work on /opt/airflow/dags/api.py
[2025-03-12T06:33:41.310+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:33:41.313+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:33:41.313+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:33:41.322+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:33:41.317+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:33:41.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:33:41.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-03-12T06:34:11.658+0000] {processor.py:157} INFO - Started process (PID=322) to work on /opt/airflow/dags/api.py
[2025-03-12T06:34:11.661+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:34:11.664+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:34:11.664+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:34:11.676+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:34:11.671+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:34:11.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:34:11.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.035 seconds
[2025-03-12T06:34:41.953+0000] {processor.py:157} INFO - Started process (PID=331) to work on /opt/airflow/dags/api.py
[2025-03-12T06:34:41.958+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:34:41.963+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:34:41.962+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:34:41.975+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:34:41.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:34:41.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:34:41.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.043 seconds
[2025-03-12T06:35:12.195+0000] {processor.py:157} INFO - Started process (PID=340) to work on /opt/airflow/dags/api.py
[2025-03-12T06:35:12.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:35:12.205+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:35:12.204+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:35:12.213+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:35:12.212+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:35:12.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:35:12.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.040 seconds
[2025-03-12T06:35:42.430+0000] {processor.py:157} INFO - Started process (PID=348) to work on /opt/airflow/dags/api.py
[2025-03-12T06:35:42.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:35:42.436+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:35:42.436+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:35:42.449+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:35:42.445+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:35:42.449+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:35:42.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.041 seconds
[2025-03-12T06:36:12.800+0000] {processor.py:157} INFO - Started process (PID=357) to work on /opt/airflow/dags/api.py
[2025-03-12T06:36:12.803+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:36:12.805+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:36:12.805+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:36:12.813+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:36:12.813+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:36:12.814+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:36:12.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.027 seconds
[2025-03-12T06:36:36.014+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/api.py
[2025-03-12T06:36:36.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:36:36.024+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:36:36.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:36:36.040+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:36:36.030+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:36:36.040+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:36:36.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.055 seconds
[2025-03-12T06:37:06.381+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/api.py
[2025-03-12T06:37:06.384+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:37:06.387+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:37:06.386+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:37:06.398+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:37:06.394+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:37:06.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:37:06.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.035 seconds
[2025-03-12T06:37:36.718+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/api.py
[2025-03-12T06:37:36.721+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:37:36.723+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:37:36.723+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:37:36.730+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:37:36.726+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:37:36.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:37:36.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:38:06.954+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/api.py
[2025-03-12T06:38:06.958+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:38:06.961+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:38:06.960+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:38:06.966+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:38:06.964+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:38:06.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:38:06.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:38:37.121+0000] {processor.py:157} INFO - Started process (PID=76) to work on /opt/airflow/dags/api.py
[2025-03-12T06:38:37.123+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:38:37.124+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:38:37.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:38:37.132+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:38:37.128+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:38:37.132+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:38:37.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.026 seconds
[2025-03-12T06:39:07.442+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/api.py
[2025-03-12T06:39:07.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:39:07.446+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:39:07.446+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:39:07.450+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:39:07.449+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:39:07.451+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:39:07.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.026 seconds
[2025-03-12T06:39:37.781+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/api.py
[2025-03-12T06:39:37.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:39:37.787+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:39:37.786+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:39:37.798+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:39:37.793+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:39:37.798+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:39:37.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-03-12T06:40:08.121+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/api.py
[2025-03-12T06:40:08.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:40:08.124+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:40:08.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:40:08.129+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:40:08.127+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:40:08.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:40:08.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.023 seconds
[2025-03-12T06:40:38.502+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/api.py
[2025-03-12T06:40:38.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:40:38.506+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:40:38.506+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:40:38.517+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:40:38.516+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:40:38.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:40:38.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-03-12T06:41:08.848+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/api.py
[2025-03-12T06:41:08.850+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:41:08.852+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:41:08.852+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:41:08.858+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:41:08.856+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:41:08.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:41:08.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:41:39.188+0000] {processor.py:157} INFO - Started process (PID=130) to work on /opt/airflow/dags/api.py
[2025-03-12T06:41:39.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:41:39.193+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:41:39.193+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:41:39.201+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:41:39.197+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:41:39.201+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:41:39.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.028 seconds
[2025-03-12T06:42:09.504+0000] {processor.py:157} INFO - Started process (PID=139) to work on /opt/airflow/dags/api.py
[2025-03-12T06:42:09.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:42:09.508+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:42:09.508+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:42:09.516+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:42:09.512+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:42:09.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:42:09.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:42:39.776+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/api.py
[2025-03-12T06:42:39.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:42:39.780+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:42:39.780+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:42:39.784+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:42:39.783+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:42:39.785+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:42:39.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.027 seconds
[2025-03-12T06:43:10.115+0000] {processor.py:157} INFO - Started process (PID=157) to work on /opt/airflow/dags/api.py
[2025-03-12T06:43:10.116+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:43:10.120+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:43:10.119+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:43:10.131+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:43:10.129+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:43:10.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:43:10.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.047 seconds
[2025-03-12T06:43:40.429+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/api.py
[2025-03-12T06:43:40.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:43:40.434+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:43:40.434+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:43:40.438+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:43:40.438+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:43:40.439+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:43:40.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:44:10.778+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/api.py
[2025-03-12T06:44:10.781+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:44:10.784+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:44:10.784+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:44:10.794+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:44:10.790+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:44:10.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:44:10.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.045 seconds
[2025-03-12T06:44:41.147+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/api.py
[2025-03-12T06:44:41.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:44:41.154+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:44:41.154+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:44:41.177+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:44:41.170+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:44:41.177+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:44:41.198+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.058 seconds
[2025-03-12T06:45:11.519+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/api.py
[2025-03-12T06:45:11.520+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:45:11.522+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:45:11.522+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:45:11.525+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:45:11.524+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:45:11.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:45:11.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.025 seconds
[2025-03-12T06:45:41.856+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/api.py
[2025-03-12T06:45:41.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:45:41.861+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:45:41.861+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:45:41.869+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:45:41.867+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:45:41.871+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:45:41.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.039 seconds
[2025-03-12T06:46:12.029+0000] {processor.py:157} INFO - Started process (PID=218) to work on /opt/airflow/dags/api.py
[2025-03-12T06:46:12.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:46:12.033+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:46:12.032+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:46:12.042+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:46:12.041+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:46:12.043+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:46:12.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.027 seconds
[2025-03-12T06:46:42.303+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/api.py
[2025-03-12T06:46:42.305+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:46:42.307+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:46:42.307+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:46:42.322+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:46:42.315+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:46:42.325+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:46:42.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.040 seconds
[2025-03-12T06:47:12.657+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/api.py
[2025-03-12T06:47:12.658+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:47:12.661+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:47:12.661+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:47:12.667+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:47:12.666+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:47:12.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:47:12.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.025 seconds
[2025-03-12T06:47:42.966+0000] {processor.py:157} INFO - Started process (PID=244) to work on /opt/airflow/dags/api.py
[2025-03-12T06:47:42.969+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:47:42.972+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:47:42.972+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:47:42.980+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:47:42.979+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:47:42.980+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:47:42.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.032 seconds
[2025-03-12T06:48:13.332+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/api.py
[2025-03-12T06:48:13.334+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:48:13.337+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:48:13.337+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:48:13.343+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:48:13.342+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:48:13.343+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:48:13.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:48:43.553+0000] {processor.py:157} INFO - Started process (PID=262) to work on /opt/airflow/dags/api.py
[2025-03-12T06:48:43.554+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:48:43.557+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:48:43.556+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:48:43.571+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:48:43.560+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:48:43.573+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:48:43.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-03-12T06:49:13.805+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/api.py
[2025-03-12T06:49:13.806+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:49:13.808+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:49:13.807+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:49:13.813+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:49:13.812+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:49:13.813+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:49:13.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.024 seconds
[2025-03-12T06:49:44.083+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/api.py
[2025-03-12T06:49:44.086+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:49:44.087+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:49:44.087+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:49:44.094+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:49:44.090+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:49:44.095+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:49:44.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:50:14.421+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/api.py
[2025-03-12T06:50:14.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:50:14.426+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:50:14.426+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:50:14.434+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:50:14.430+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:50:14.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:50:14.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.031 seconds
[2025-03-12T06:53:39.295+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/api.py
[2025-03-12T06:53:39.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:53:39.298+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:53:39.298+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:53:39.305+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:53:39.302+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:53:39.306+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:53:39.321+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.027 seconds
[2025-03-12T06:54:09.592+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/api.py
[2025-03-12T06:54:09.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:54:09.595+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:54:09.595+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:54:09.605+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:54:09.604+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:54:09.606+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:54:09.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.029 seconds
[2025-03-12T06:54:39.905+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/api.py
[2025-03-12T06:54:39.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:54:39.908+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:54:39.908+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:54:39.919+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:54:39.915+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:54:39.919+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:54:39.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.028 seconds
[2025-03-12T06:55:10.240+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/api.py
[2025-03-12T06:55:10.242+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-03-12T06:55:10.243+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:55:10.243+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-03-12T06:55:10.248+0000] {logging_mixin.py:154} INFO - [2025-03-12T06:55:10.247+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
[2025-03-12T06:55:10.249+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-03-12T06:55:10.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/api.py took 0.022 seconds
